# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Makin it easy
tagline:             'A Jekyll theme'
description:         '  Thanks for all the fish '
url:                 http://ezrider.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mike Beaulieu
  url:               
  email:             michael.e.beaulieu@gmail.com

# Custom vars
version:             1.0.0

collections:
  statusupdates:
    output: true
